name: carbon
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - nb_conda_kernels
  - jupyter_contrib_nbextensions

  - pip
  - pip:
      - leafsim
